title: Phosphor Notes
description: A minimal, secure, and focused knowledge studio for the modern thinker.

# Site configuration
url: https://phosphor.adamcaudill.com
baseurl: ""

# Footer
footer_content: 'Copyright &copy; 2026 <a href="https://adamcaudill.com">Adam Caudill</a>.'

# GitHub
github_url: https://github.com/adcaudill/phosphor-notes

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-gfm-admonitions

highlighter: rouge

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "index.md"
    values:
      layout: "home"
  - scope:
      path: "docs/**/*.md"
    values:
      layout: "page"

# Excluding files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .git
  - .github
